[env:m5stack-fire]
platform           = espressif32@^6.7.0
board              = m5stack-fire
framework          = arduino
monitor_speed      = 115200
upload_speed       = 921600

board_build.partitions = default_16MB.csv
board_build.f_flash    = 80000000L
board_build.flash_mode = dio

build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
  -DCONFIG_BT_ENABLED=1
  -DCONFIG_BT_BLE_ENABLED=1
  -DCONFIG_BT_HID_HOST_ENABLED=1
  -DCONFIG_BT_GATTC_ENABLE=1
  -DCONFIG_BT_SMP_ENABLE=1
  -DARDUINO_USB_CDC_ON_BOOT=0

lib_deps =
  m5stack/M5Stack@^0.4.6

monitor_filters = esp32_exception_decoder, time
